1. Importando pacotes

In [1]:
import re 
import pandas as pd
import numpy as np
import unicodedata
import seaborn as sns 
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import joblib

In [2]:
sns.set_style('whitegrid')

2. Carregando e compreendendo os dados

In [3]:
nome_do_arquivo_csv = 'dataset.csv'
df = pd.read_csv(nome_do_arquivo_csv)

In [4]:
df.shape

(500, 3)

In [6]:
df.head()

   review_id                                       texto_review sentimento
0          1  Estou muito feliz com a compra. O cadeira game...   positivo
1          2                                                NaN   negativo
2          3  Não recomendo. A entrega foi lenta e o celular...   negativo
3          4  O monitor é decepcionante. O suporte ao client...   positivo
4          5               É UM LIVRO OK PELO PRÇEO QUE PAGUEI.   negativo

In [8]:
df.sample(10) # amostra aleatória

     review_id                                       texto_review sentimento
368        369  Ótimo custo-benefício. O teclado é excelente e...   positivo
213        214  Ótimo custo-benefício. O notebook é excelente ...   positivo
491        492  Amei o monitor! A qualidade é ótima e a entreg...   positivo
96          97  Péssima experiência. O cadeira gamer quebrou n...   positivo
351        352  NÃO RECOMENDO. A ENTREGA ATRASOU MUITO E O NOT...   negativo
232        233  Não recomendo. A entrega demorou uma eternidad...   positivo
25          26  A cor do fone de ouivdo é um pouco diferente d...   negativo
218        219  Ótimo custo-benefício. O notebook é excelente ...   negativo
242        243  Estou muito feliz com a compra. O monitor é in...   positivo
110        111  Amei o fone de ouvido! A qualidade é nicrível ...   positivo